[package]
name = "xtest"
version = "0.0.0"
authors = ["Matthew James Briggs <matthew.james.briggs@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.48"
serde_plain = "0.3.0"
xdoc = {path = "../xdoc", features = ["serde"] }
